// <auto-generated />
using ASP_NET_assignments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP_NET_assignments.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220601091442_Added City Model")]
    partial class AddedCityModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP_NET_assignments.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 2140680517,
                            Name = "Göteborg"
                        },
                        new
                        {
                            Id = 318113213,
                            Name = "Staden"
                        },
                        new
                        {
                            Id = 1377319211,
                            Name = "Skogen"
                        },
                        new
                        {
                            Id = 46947043,
                            Name = "Luftslottet"
                        });
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityName");

                    b.ToTable("PeopleDataTable");

                    b.HasData(
                        new
                        {
                            Id = 426844326,
                            CityName = "Göteborg",
                            Name = "Jens Eresund",
                            Phonenumber = "+46706845909"
                        },
                        new
                        {
                            Id = 800789915,
                            CityName = "Staden",
                            Name = "Abel Abrahamsson",
                            Phonenumber = "+00123456789"
                        },
                        new
                        {
                            Id = 1552201324,
                            CityName = "Skogen",
                            Name = "Bror Björn",
                            Phonenumber = "+5555555555"
                        },
                        new
                        {
                            Id = 1012430503,
                            CityName = "Luftslottet",
                            Name = "Örjan Örn",
                            Phonenumber = "1111111111"
                        });
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.Person", b =>
                {
                    b.HasOne("ASP_NET_assignments.Models.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
