// <auto-generated />
using ASP_NET_assignments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP_NET_assignments.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220607120639_Added_PersonLanguage")]
    partial class Added_PersonLanguage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP_NET_assignments.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryName");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1492625250,
                            CountryName = "Sverige",
                            Name = "Göteborg"
                        },
                        new
                        {
                            Id = 926749618,
                            CountryName = "Sverige",
                            Name = "Staden"
                        },
                        new
                        {
                            Id = 741622396,
                            CountryName = "Norge",
                            Name = "Skogen"
                        },
                        new
                        {
                            Id = 1609786201,
                            CountryName = "Ingenstans",
                            Name = "Luftslottet"
                        });
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1375161546,
                            Name = "Sverige"
                        },
                        new
                        {
                            Id = 1987401714,
                            Name = "Norge"
                        },
                        new
                        {
                            Id = 780588204,
                            Name = "Ingenstans"
                        });
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1686208453,
                            Name = "Svenska"
                        },
                        new
                        {
                            Id = 1815848149,
                            Name = "Engelska"
                        },
                        new
                        {
                            Id = 1115537332,
                            Name = "Spanska"
                        });
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityName");

                    b.ToTable("PeopleDataTable");

                    b.HasData(
                        new
                        {
                            Id = 1822467822,
                            CityName = "Göteborg",
                            Name = "Jens Eresund",
                            Phonenumber = "+46706845909"
                        },
                        new
                        {
                            Id = 1180735110,
                            CityName = "Staden",
                            Name = "Abel Abrahamsson",
                            Phonenumber = "+00123456789"
                        },
                        new
                        {
                            Id = 1153083005,
                            CityName = "Skogen",
                            Name = "Bror Björn",
                            Phonenumber = "+5555555555"
                        },
                        new
                        {
                            Id = 425975129,
                            CityName = "Luftslottet",
                            Name = "Örjan Örn",
                            Phonenumber = "1111111111"
                        });
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.PersonLanguage", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("PersonLanguages");

                    b.HasData(
                        new
                        {
                            PersonId = 1822467822,
                            LanguageId = 1815848149
                        },
                        new
                        {
                            PersonId = 1822467822,
                            LanguageId = 1115537332
                        },
                        new
                        {
                            PersonId = 1180735110,
                            LanguageId = 1815848149
                        },
                        new
                        {
                            PersonId = 1180735110,
                            LanguageId = 1686208453
                        },
                        new
                        {
                            PersonId = 1153083005,
                            LanguageId = 1815848149
                        },
                        new
                        {
                            PersonId = 1153083005,
                            LanguageId = 1115537332
                        },
                        new
                        {
                            PersonId = 425975129,
                            LanguageId = 1815848149
                        },
                        new
                        {
                            PersonId = 425975129,
                            LanguageId = 1115537332
                        });
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.City", b =>
                {
                    b.HasOne("ASP_NET_assignments.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.Person", b =>
                {
                    b.HasOne("ASP_NET_assignments.Models.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP_NET_assignments.Models.PersonLanguage", b =>
                {
                    b.HasOne("ASP_NET_assignments.Models.Language", "Language")
                        .WithMany("PersonLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_NET_assignments.Models.Person", "Speaker")
                        .WithMany("PersonLanguages")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
